services:
  distributed-storage:
    container_name: csc466
    networks:
      - ds
    build:
      context: .
    cap_add:
      - NET_ADMIN
    entrypoint: >
      sh -c '
        if [ ! -z "${LATENCY}" ]; then
          apt-get update && apt-get install -y iproute2
          tc qdisc add dev lo root netem delay "${LATENCY}ms"
          tc qdisc change dev lo root pfifo limit 10000
        fi
        ./runsim.sh
      '
    deploy:
      resources:
        limits:
          cpus: "0"
          memory: 0G
        reservations:
          cpus: "0"
          memory: 0G
    volumes:
      - ./output/:/app/tmp/output/
      - ./log/:/app/tmp/log/
      - ./config/:/app/config/

networks:
  ds:
    driver: bridge
    name: ds
