user:
  x-small: 10
  small: 10
  medium: 10
  large: 10
  x-large: 5
  xx-large: 5

cluster:
  node: 10

load-balancer:
  # acceptable values:
  #   - rr: simple round robin
  #   - lrt: least response time
  #   - lc: least connections
  algo: lrt
  local-port: 8000
