services:
  discovery:
    container_name: discovery
    build:
      context: .
      dockerfile: ./dockerfiles/discovery.Dockerfile
    environment:
      - SOCKET_PORT=8080
    networks:
      static-network:
        ipv4_address: 172.20.128.2

  node-1:
    container_name: node-1
    build:
      context: .
      dockerfile: ./dockerfiles/node.Dockerfile
    depends_on:
      discovery:
        condition: service_started
    cap_add:
      - NET_ADMIN
    environment:
      - SOCKET_PORT=8080
    networks:
      static-network:
        ipv4_address: 172.20.128.3

  node-2:
    container_name: node-2
    build:
      context: .
      dockerfile: ./dockerfiles/node.Dockerfile
    depends_on:
      discovery:
        condition: service_started
    environment:
      - SOCKET_PORT=8080
    networks:
      static-network:
        ipv4_address: 172.20.128.4

  node-3:
    container_name: node-3
    build:
      context: .
      dockerfile: ./dockerfiles/node.Dockerfile
    depends_on:
      discovery:
        condition: service_started
    environment:
      - SOCKET_PORT=8080
    networks:
      static-network:
        ipv4_address: 172.20.128.5

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
