version: "3"

services:
  node-1:
    container_name: node-1
    build:
      context: .
      dockerfile: ./dockerfiles/node.Dockerfile
    environment:
      - SOCKET_PORT=8080
    # stdin_open: true # same as docker run -i
    # tty: true # same as docker run -t
    networks:
      static-network:
        ipv4_address: 172.20.128.3

  node-2:
    container_name: discovery
    build:
      context: .
      dockerfile: ./dockerfiles/discovery.Dockerfile
    environment:
      - SOCKET_PORT=8080
    networks:
      static-network:
        ipv4_address: 172.20.128.2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
