user:
  x-small: 1
  small: 0
  medium: 0
  large: 0
  x-large: 0
  xx-large: 0
  interval: 0

cluster:
  node: 10

load-balancer:
  # allowed values: simple-round-robin, least-connections, least-response-time
  algo: simple-round-robin
  local-port: 8000

experiment:
  name: test1
  latency: 10
  homogeneous: false
  # in nanoseconds
  overhead-param: 1000
