user:
  x-small: 0
  small: 0
  medium: 0
  large: 0
  x-large: 300
  xx-large: 0
  interval: 10

cluster:
  node: 20
  capacity: 10

load-balancer:
  # allowed values: simple-round-robin, least-connections, least-response-time
  algo: least-connections
  local-port: 8000

experiment:
  name: test1
  latency: 10
  homogeneous: false
  # in nanoseconds
  overhead-param: 1000
