user:
  x-small: 100
  small: 20
  medium: 10
  large: 10
  x-large: 1
  xx-large: 1
  interval: 10

cluster:
  node: 10

load-balancer:
  # allowed values: simple-round-robin, least-connections, least-response-time
  algo: simple-round-robin
  local-port: 8000

experiment:
  name: test1
  latency: 10
  homogeneous: true