user:
  x-small: 1
  small: 1
  medium: 1
  large: 1
  x-large: 1
  xx-large: 1

cluster:
  node: 10

load-balancer:
  # allowed values: simple-round-robin, least-connections, least-response-time
  algo: least-response-time
  local-port: 8000
