user:
  small: 338
  medium: 327
  large: 335
  x-large: 0
  xx-large: 0
  interval: 20

cluster:
  node: 10
  capacity: 5

load-balancer:
  algo: simple-round-robin
  local-port: 8000

experiment:
  name: exp-rr-lat-25-homog-false-int-20-fsz-v-rate-50
  latency: 25
  homogeneous: false
  overhead-param: 1000