name: CI

on:
  push:

  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Code Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: unused dependencies
        run: go mod tidy; git diff --exit-code

      - name: format checker
        run: |
          badfiles=$(gofmt -l .);\
          [[ -z $(gofmt -l .) ]] || (echo 'files with bad code formatting:'; echo $badfiles; exit 1)

      - name: test runner
        run: go test -v ./...

      - name: build cluster binary
        run: go build ./cmd/cluster

      - name: build loadbalance binary
        run: go build ./cmd/loadbalance

      - name: build user binary
        run: go build ./cmd/user

      - name: build datainit binary
        run: go build ./cmd/datainit
